# nextpnr -- Next Generation Place and Route
#
# Copyright (C) 2025 Aki Van Ness <aki@lethalbit.net>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

from __future__ import annotations

from enum       import Enum, Flag, auto, unique
from typing     import SupportsInt, SupportsFloat, TypeAlias, overload

from .types     import IdString, PlaceStrength

__all__ = (
	'ConstID',
	'Location',
	'BelID',
	'BelPin',
	'WireID',
	'PipID',
	'PipMap',
	'GroupID',
	'GroupIDType',
	'DecalID',
	'DecalIDType',
	'DecalXY',
	'ArchNetInfo',
	'ArchCellInfo',
	'ArchCellInfoCombInfo',
	'ArchCellInfoFFInfo',
	'ArchCellInfoRAMInfo',
	'ArchCellInfoMultInfo',
	'ArchCellInfoCombFlags',
	'ArchCellInfoFFFlags'
)

@unique
class ConstID(Enum):
	ID_NONE = auto()
	A0 = auto()
	B0 = auto()
	C0 = auto()
	D0 = auto()
	A1 = auto()
	B1 = auto()
	C1 = auto()
	D1 = auto()
	M0 = auto()
	M1 = auto()
	FCI = auto()
	FXA = auto()
	FXB = auto()
	CLK = auto()
	LSR = auto()
	CE = auto()
	DI0 = auto()
	DI1 = auto()
	WD0 = auto()
	WD1 = auto()
	WAD0 = auto()
	WAD1 = auto()
	WAD2 = auto()
	WAD3 = auto()
	WRE = auto()
	WCK = auto()
	F0 = auto()
	Q0 = auto()
	F1 = auto()
	Q1 = auto()
	FCO = auto()
	OFX0 = auto()
	OFX1 = auto()
	WDO0 = auto()
	WDO1 = auto()
	WDO2 = auto()
	WDO3 = auto()
	WADO0 = auto()
	WADO1 = auto()
	WADO2 = auto()
	WADO3 = auto()
	I = auto()
	O = auto()
	T = auto()
	B = auto()
	TRELLIS_SLICE = auto()
	TRELLIS_IO = auto()
	DCCA = auto()
	CLKMUX = auto()
	LSRMUX = auto()
	SRMODE = auto()
	CLKI = auto()
	CLKO = auto()
	DP16KD = auto()
	DIA0 = auto()
	DIA1 = auto()
	DIA2 = auto()
	DIA3 = auto()
	DIA4 = auto()
	DIA5 = auto()
	DIA6 = auto()
	DIA7 = auto()
	DIA8 = auto()
	DIA9 = auto()
	DIA10 = auto()
	DIA11 = auto()
	DIA12 = auto()
	DIA13 = auto()
	DIA14 = auto()
	DIA15 = auto()
	DIA16 = auto()
	DIA17 = auto()
	ADA0 = auto()
	ADA1 = auto()
	ADA2 = auto()
	ADA3 = auto()
	ADA4 = auto()
	ADA5 = auto()
	ADA6 = auto()
	ADA7 = auto()
	ADA8 = auto()
	ADA9 = auto()
	ADA10 = auto()
	ADA11 = auto()
	ADA12 = auto()
	ADA13 = auto()
	CEA = auto()
	OCEA = auto()
	CLKA = auto()
	WEA = auto()
	CSA2 = auto()
	CSA1 = auto()
	CSA0 = auto()
	RSTA = auto()
	DIB0 = auto()
	DIB1 = auto()
	DIB2 = auto()
	DIB3 = auto()
	DIB4 = auto()
	DIB5 = auto()
	DIB6 = auto()
	DIB7 = auto()
	DIB8 = auto()
	DIB9 = auto()
	DIB10 = auto()
	DIB11 = auto()
	DIB12 = auto()
	DIB13 = auto()
	DIB14 = auto()
	DIB15 = auto()
	DIB16 = auto()
	DIB17 = auto()
	ADB0 = auto()
	ADB1 = auto()
	ADB2 = auto()
	ADB3 = auto()
	ADB4 = auto()
	ADB5 = auto()
	ADB6 = auto()
	ADB7 = auto()
	ADB8 = auto()
	ADB9 = auto()
	ADB10 = auto()
	ADB11 = auto()
	ADB12 = auto()
	ADB13 = auto()
	CEB = auto()
	OCEB = auto()
	CLKB = auto()
	WEB = auto()
	CSB2 = auto()
	CSB1 = auto()
	CSB0 = auto()
	RSTB = auto()
	DOA0 = auto()
	DOA1 = auto()
	DOA2 = auto()
	DOA3 = auto()
	DOA4 = auto()
	DOA5 = auto()
	DOA6 = auto()
	DOA7 = auto()
	DOA8 = auto()
	DOA9 = auto()
	DOA10 = auto()
	DOA11 = auto()
	DOA12 = auto()
	DOA13 = auto()
	DOA14 = auto()
	DOA15 = auto()
	DOA16 = auto()
	DOA17 = auto()
	DOB0 = auto()
	DOB1 = auto()
	DOB2 = auto()
	DOB3 = auto()
	DOB4 = auto()
	DOB5 = auto()
	DOB6 = auto()
	DOB7 = auto()
	DOB8 = auto()
	DOB9 = auto()
	DOB10 = auto()
	DOB11 = auto()
	DOB12 = auto()
	DOB13 = auto()
	DOB14 = auto()
	DOB15 = auto()
	DOB16 = auto()
	DOB17 = auto()
	MULT18X18D = auto()
	A2 = auto()
	A3 = auto()
	A4 = auto()
	A5 = auto()
	A6 = auto()
	A7 = auto()
	A8 = auto()
	A9 = auto()
	A10 = auto()
	A11 = auto()
	A12 = auto()
	A13 = auto()
	A14 = auto()
	A15 = auto()
	A16 = auto()
	A17 = auto()
	B2 = auto()
	B3 = auto()
	B4 = auto()
	B5 = auto()
	B6 = auto()
	B7 = auto()
	B8 = auto()
	B9 = auto()
	B10 = auto()
	B11 = auto()
	B12 = auto()
	B13 = auto()
	B14 = auto()
	B15 = auto()
	B16 = auto()
	B17 = auto()
	C2 = auto()
	C3 = auto()
	C4 = auto()
	C5 = auto()
	C6 = auto()
	C7 = auto()
	C8 = auto()
	C9 = auto()
	C10 = auto()
	C11 = auto()
	C12 = auto()
	C13 = auto()
	C14 = auto()
	C15 = auto()
	C16 = auto()
	C17 = auto()
	SIGNEDA = auto()
	SIGNEDB = auto()
	SOURCEA = auto()
	SOURCEB = auto()
	CLK0 = auto()
	CLK1 = auto()
	CLK2 = auto()
	CLK3 = auto()
	CE0 = auto()
	CE1 = auto()
	CE2 = auto()
	CE3 = auto()
	RST0 = auto()
	RST1 = auto()
	RST2 = auto()
	RST3 = auto()
	SRIA0 = auto()
	SRIA1 = auto()
	SRIA2 = auto()
	SRIA3 = auto()
	SRIA4 = auto()
	SRIA5 = auto()
	SRIA6 = auto()
	SRIA7 = auto()
	SRIA8 = auto()
	SRIA9 = auto()
	SRIA10 = auto()
	SRIA11 = auto()
	SRIA12 = auto()
	SRIA13 = auto()
	SRIA14 = auto()
	SRIA15 = auto()
	SRIA16 = auto()
	SRIA17 = auto()
	SRIB0 = auto()
	SRIB1 = auto()
	SRIB2 = auto()
	SRIB3 = auto()
	SRIB4 = auto()
	SRIB5 = auto()
	SRIB6 = auto()
	SRIB7 = auto()
	SRIB8 = auto()
	SRIB9 = auto()
	SRIB10 = auto()
	SRIB11 = auto()
	SRIB12 = auto()
	SRIB13 = auto()
	SRIB14 = auto()
	SRIB15 = auto()
	SRIB16 = auto()
	SRIB17 = auto()
	SROA0 = auto()
	SROA1 = auto()
	SROA2 = auto()
	SROA3 = auto()
	SROA4 = auto()
	SROA5 = auto()
	SROA6 = auto()
	SROA7 = auto()
	SROA8 = auto()
	SROA9 = auto()
	SROA10 = auto()
	SROA11 = auto()
	SROA12 = auto()
	SROA13 = auto()
	SROA14 = auto()
	SROA15 = auto()
	SROA16 = auto()
	SROA17 = auto()
	SROB0 = auto()
	SROB1 = auto()
	SROB2 = auto()
	SROB3 = auto()
	SROB4 = auto()
	SROB5 = auto()
	SROB6 = auto()
	SROB7 = auto()
	SROB8 = auto()
	SROB9 = auto()
	SROB10 = auto()
	SROB11 = auto()
	SROB12 = auto()
	SROB13 = auto()
	SROB14 = auto()
	SROB15 = auto()
	SROB16 = auto()
	SROB17 = auto()
	ROA0 = auto()
	ROA1 = auto()
	ROA2 = auto()
	ROA3 = auto()
	ROA4 = auto()
	ROA5 = auto()
	ROA6 = auto()
	ROA7 = auto()
	ROA8 = auto()
	ROA9 = auto()
	ROA10 = auto()
	ROA11 = auto()
	ROA12 = auto()
	ROA13 = auto()
	ROA14 = auto()
	ROA15 = auto()
	ROA16 = auto()
	ROA17 = auto()
	ROB0 = auto()
	ROB1 = auto()
	ROB2 = auto()
	ROB3 = auto()
	ROB4 = auto()
	ROB5 = auto()
	ROB6 = auto()
	ROB7 = auto()
	ROB8 = auto()
	ROB9 = auto()
	ROB10 = auto()
	ROB11 = auto()
	ROB12 = auto()
	ROB13 = auto()
	ROB14 = auto()
	ROB15 = auto()
	ROB16 = auto()
	ROB17 = auto()
	ROC0 = auto()
	ROC1 = auto()
	ROC2 = auto()
	ROC3 = auto()
	ROC4 = auto()
	ROC5 = auto()
	ROC6 = auto()
	ROC7 = auto()
	ROC8 = auto()
	ROC9 = auto()
	ROC10 = auto()
	ROC11 = auto()
	ROC12 = auto()
	ROC13 = auto()
	ROC14 = auto()
	ROC15 = auto()
	ROC16 = auto()
	ROC17 = auto()
	P0 = auto()
	P1 = auto()
	P2 = auto()
	P3 = auto()
	P4 = auto()
	P5 = auto()
	P6 = auto()
	P7 = auto()
	P8 = auto()
	P9 = auto()
	P10 = auto()
	P11 = auto()
	P12 = auto()
	P13 = auto()
	P14 = auto()
	P15 = auto()
	P16 = auto()
	P17 = auto()
	P18 = auto()
	P19 = auto()
	P20 = auto()
	P21 = auto()
	P22 = auto()
	P23 = auto()
	P24 = auto()
	P25 = auto()
	P26 = auto()
	P27 = auto()
	P28 = auto()
	P29 = auto()
	P30 = auto()
	P31 = auto()
	P32 = auto()
	P33 = auto()
	P34 = auto()
	P35 = auto()
	SIGNEDP = auto()
	ALU54B = auto()
	SIGNEDIA = auto()
	SIGNEDIB = auto()
	SIGNEDCIN = auto()
	A18 = auto()
	A19 = auto()
	A20 = auto()
	A21 = auto()
	A22 = auto()
	A23 = auto()
	A24 = auto()
	A25 = auto()
	A26 = auto()
	A27 = auto()
	A28 = auto()
	A29 = auto()
	A30 = auto()
	A31 = auto()
	A32 = auto()
	A33 = auto()
	A34 = auto()
	A35 = auto()
	B18 = auto()
	B19 = auto()
	B20 = auto()
	B21 = auto()
	B22 = auto()
	B23 = auto()
	B24 = auto()
	B25 = auto()
	B26 = auto()
	B27 = auto()
	B28 = auto()
	B29 = auto()
	B30 = auto()
	B31 = auto()
	B32 = auto()
	B33 = auto()
	B34 = auto()
	B35 = auto()
	C18 = auto()
	C19 = auto()
	C20 = auto()
	C21 = auto()
	C22 = auto()
	C23 = auto()
	C24 = auto()
	C25 = auto()
	C26 = auto()
	C27 = auto()
	C28 = auto()
	C29 = auto()
	C30 = auto()
	C31 = auto()
	C32 = auto()
	C33 = auto()
	C34 = auto()
	C35 = auto()
	C36 = auto()
	C37 = auto()
	C38 = auto()
	C39 = auto()
	C40 = auto()
	C41 = auto()
	C42 = auto()
	C43 = auto()
	C44 = auto()
	C45 = auto()
	C46 = auto()
	C47 = auto()
	C48 = auto()
	C49 = auto()
	C50 = auto()
	C51 = auto()
	C52 = auto()
	C53 = auto()
	CFB0 = auto()
	CFB1 = auto()
	CFB2 = auto()
	CFB3 = auto()
	CFB4 = auto()
	CFB5 = auto()
	CFB6 = auto()
	CFB7 = auto()
	CFB8 = auto()
	CFB9 = auto()
	CFB10 = auto()
	CFB11 = auto()
	CFB12 = auto()
	CFB13 = auto()
	CFB14 = auto()
	CFB15 = auto()
	CFB16 = auto()
	CFB17 = auto()
	CFB18 = auto()
	CFB19 = auto()
	CFB20 = auto()
	CFB21 = auto()
	CFB22 = auto()
	CFB23 = auto()
	CFB24 = auto()
	CFB25 = auto()
	CFB26 = auto()
	CFB27 = auto()
	CFB28 = auto()
	CFB29 = auto()
	CFB30 = auto()
	CFB31 = auto()
	CFB32 = auto()
	CFB33 = auto()
	CFB34 = auto()
	CFB35 = auto()
	CFB36 = auto()
	CFB37 = auto()
	CFB38 = auto()
	CFB39 = auto()
	CFB40 = auto()
	CFB41 = auto()
	CFB42 = auto()
	CFB43 = auto()
	CFB44 = auto()
	CFB45 = auto()
	CFB46 = auto()
	CFB47 = auto()
	CFB48 = auto()
	CFB49 = auto()
	CFB50 = auto()
	CFB51 = auto()
	CFB52 = auto()
	CFB53 = auto()
	MA0 = auto()
	MA1 = auto()
	MA2 = auto()
	MA3 = auto()
	MA4 = auto()
	MA5 = auto()
	MA6 = auto()
	MA7 = auto()
	MA8 = auto()
	MA9 = auto()
	MA10 = auto()
	MA11 = auto()
	MA12 = auto()
	MA13 = auto()
	MA14 = auto()
	MA15 = auto()
	MA16 = auto()
	MA17 = auto()
	MA18 = auto()
	MA19 = auto()
	MA20 = auto()
	MA21 = auto()
	MA22 = auto()
	MA23 = auto()
	MA24 = auto()
	MA25 = auto()
	MA26 = auto()
	MA27 = auto()
	MA28 = auto()
	MA29 = auto()
	MA30 = auto()
	MA31 = auto()
	MA32 = auto()
	MA33 = auto()
	MA34 = auto()
	MA35 = auto()
	MB0 = auto()
	MB1 = auto()
	MB2 = auto()
	MB3 = auto()
	MB4 = auto()
	MB5 = auto()
	MB6 = auto()
	MB7 = auto()
	MB8 = auto()
	MB9 = auto()
	MB10 = auto()
	MB11 = auto()
	MB12 = auto()
	MB13 = auto()
	MB14 = auto()
	MB15 = auto()
	MB16 = auto()
	MB17 = auto()
	MB18 = auto()
	MB19 = auto()
	MB20 = auto()
	MB21 = auto()
	MB22 = auto()
	MB23 = auto()
	MB24 = auto()
	MB25 = auto()
	MB26 = auto()
	MB27 = auto()
	MB28 = auto()
	MB29 = auto()
	MB30 = auto()
	MB31 = auto()
	MB32 = auto()
	MB33 = auto()
	MB34 = auto()
	MB35 = auto()
	CIN0 = auto()
	CIN1 = auto()
	CIN2 = auto()
	CIN3 = auto()
	CIN4 = auto()
	CIN5 = auto()
	CIN6 = auto()
	CIN7 = auto()
	CIN8 = auto()
	CIN9 = auto()
	CIN10 = auto()
	CIN11 = auto()
	CIN12 = auto()
	CIN13 = auto()
	CIN14 = auto()
	CIN15 = auto()
	CIN16 = auto()
	CIN17 = auto()
	CIN18 = auto()
	CIN19 = auto()
	CIN20 = auto()
	CIN21 = auto()
	CIN22 = auto()
	CIN23 = auto()
	CIN24 = auto()
	CIN25 = auto()
	CIN26 = auto()
	CIN27 = auto()
	CIN28 = auto()
	CIN29 = auto()
	CIN30 = auto()
	CIN31 = auto()
	CIN32 = auto()
	CIN33 = auto()
	CIN34 = auto()
	CIN35 = auto()
	CIN36 = auto()
	CIN37 = auto()
	CIN38 = auto()
	CIN39 = auto()
	CIN40 = auto()
	CIN41 = auto()
	CIN42 = auto()
	CIN43 = auto()
	CIN44 = auto()
	CIN45 = auto()
	CIN46 = auto()
	CIN47 = auto()
	CIN48 = auto()
	CIN49 = auto()
	CIN50 = auto()
	CIN51 = auto()
	CIN52 = auto()
	CIN53 = auto()
	OP0 = auto()
	OP1 = auto()
	OP2 = auto()
	OP3 = auto()
	OP4 = auto()
	OP5 = auto()
	OP6 = auto()
	OP7 = auto()
	OP8 = auto()
	OP9 = auto()
	OP10 = auto()
	R0 = auto()
	R1 = auto()
	R2 = auto()
	R3 = auto()
	R4 = auto()
	R5 = auto()
	R6 = auto()
	R7 = auto()
	R8 = auto()
	R9 = auto()
	R10 = auto()
	R11 = auto()
	R12 = auto()
	R13 = auto()
	R14 = auto()
	R15 = auto()
	R16 = auto()
	R17 = auto()
	R18 = auto()
	R19 = auto()
	R20 = auto()
	R21 = auto()
	R22 = auto()
	R23 = auto()
	R24 = auto()
	R25 = auto()
	R26 = auto()
	R27 = auto()
	R28 = auto()
	R29 = auto()
	R30 = auto()
	R31 = auto()
	R32 = auto()
	R33 = auto()
	R34 = auto()
	R35 = auto()
	R36 = auto()
	R37 = auto()
	R38 = auto()
	R39 = auto()
	R40 = auto()
	R41 = auto()
	R42 = auto()
	R43 = auto()
	R44 = auto()
	R45 = auto()
	R46 = auto()
	R47 = auto()
	R48 = auto()
	R49 = auto()
	R50 = auto()
	R51 = auto()
	R52 = auto()
	R53 = auto()
	CO0 = auto()
	CO1 = auto()
	CO2 = auto()
	CO3 = auto()
	CO4 = auto()
	CO5 = auto()
	CO6 = auto()
	CO7 = auto()
	CO8 = auto()
	CO9 = auto()
	CO10 = auto()
	CO11 = auto()
	CO12 = auto()
	CO13 = auto()
	CO14 = auto()
	CO15 = auto()
	CO16 = auto()
	CO17 = auto()
	CO18 = auto()
	CO19 = auto()
	CO20 = auto()
	CO21 = auto()
	CO22 = auto()
	CO23 = auto()
	CO24 = auto()
	CO25 = auto()
	CO26 = auto()
	CO27 = auto()
	CO28 = auto()
	CO29 = auto()
	CO30 = auto()
	CO31 = auto()
	CO32 = auto()
	CO33 = auto()
	CO34 = auto()
	CO35 = auto()
	CO36 = auto()
	CO37 = auto()
	CO38 = auto()
	CO39 = auto()
	CO40 = auto()
	CO41 = auto()
	CO42 = auto()
	CO43 = auto()
	CO44 = auto()
	CO45 = auto()
	CO46 = auto()
	CO47 = auto()
	CO48 = auto()
	CO49 = auto()
	CO50 = auto()
	CO51 = auto()
	CO52 = auto()
	CO53 = auto()
	EQZ = auto()
	EQZM = auto()
	EQOM = auto()
	EQPAT = auto()
	EQPATB = auto()
	OVER = auto()
	UNDER = auto()
	OVERUNDER = auto()
	SIGNEDR = auto()
	EHXPLLL = auto()
	CLKFB = auto()
	PHASESEL1 = auto()
	PHASESEL0 = auto()
	PHASEDIR = auto()
	PHASESTEP = auto()
	PHASELOADREG = auto()
	STDBY = auto()
	PLLWAKESYNC = auto()
	RST = auto()
	ENCLKOP = auto()
	ENCLKOS = auto()
	ENCLKOS2 = auto()
	ENCLKOS3 = auto()
	CLKOP = auto()
	CLKOS = auto()
	CLKOS2 = auto()
	CLKOS3 = auto()
	LOCK = auto()
	INTLOCK = auto()
	REFCLK = auto()
	CLKINTFB = auto()
	EXTREFB = auto()
	REFCLKP = auto()
	REFCLKN = auto()
	REFCLKO = auto()
	DCUA = auto()
	CH0_HDINP = auto()
	CH1_HDINP = auto()
	CH0_HDINN = auto()
	CH1_HDINN = auto()
	D_TXBIT_CLKP_FROM_ND = auto()
	D_TXBIT_CLKN_FROM_ND = auto()
	D_SYNC_ND = auto()
	D_TXPLL_LOL_FROM_ND = auto()
	CH0_RX_REFCLK = auto()
	CH1_RX_REFCLK = auto()
	CH0_FF_RXI_CLK = auto()
	CH1_FF_RXI_CLK = auto()
	CH0_FF_TXI_CLK = auto()
	CH1_FF_TXI_CLK = auto()
	CH0_FF_EBRD_CLK = auto()
	CH1_FF_EBRD_CLK = auto()
	CH0_FF_TX_D_0 = auto()
	CH1_FF_TX_D_0 = auto()
	CH0_FF_TX_D_1 = auto()
	CH1_FF_TX_D_1 = auto()
	CH0_FF_TX_D_2 = auto()
	CH1_FF_TX_D_2 = auto()
	CH0_FF_TX_D_3 = auto()
	CH1_FF_TX_D_3 = auto()
	CH0_FF_TX_D_4 = auto()
	CH1_FF_TX_D_4 = auto()
	CH0_FF_TX_D_5 = auto()
	CH1_FF_TX_D_5 = auto()
	CH0_FF_TX_D_6 = auto()
	CH1_FF_TX_D_6 = auto()
	CH0_FF_TX_D_7 = auto()
	CH1_FF_TX_D_7 = auto()
	CH0_FF_TX_D_8 = auto()
	CH1_FF_TX_D_8 = auto()
	CH0_FF_TX_D_9 = auto()
	CH1_FF_TX_D_9 = auto()
	CH0_FF_TX_D_10 = auto()
	CH1_FF_TX_D_10 = auto()
	CH0_FF_TX_D_11 = auto()
	CH1_FF_TX_D_11 = auto()
	CH0_FF_TX_D_12 = auto()
	CH1_FF_TX_D_12 = auto()
	CH0_FF_TX_D_13 = auto()
	CH1_FF_TX_D_13 = auto()
	CH0_FF_TX_D_14 = auto()
	CH1_FF_TX_D_14 = auto()
	CH0_FF_TX_D_15 = auto()
	CH1_FF_TX_D_15 = auto()
	CH0_FF_TX_D_16 = auto()
	CH1_FF_TX_D_16 = auto()
	CH0_FF_TX_D_17 = auto()
	CH1_FF_TX_D_17 = auto()
	CH0_FF_TX_D_18 = auto()
	CH1_FF_TX_D_18 = auto()
	CH0_FF_TX_D_19 = auto()
	CH1_FF_TX_D_19 = auto()
	CH0_FF_TX_D_20 = auto()
	CH1_FF_TX_D_20 = auto()
	CH0_FF_TX_D_21 = auto()
	CH1_FF_TX_D_21 = auto()
	CH0_FF_TX_D_22 = auto()
	CH1_FF_TX_D_22 = auto()
	CH0_FF_TX_D_23 = auto()
	CH1_FF_TX_D_23 = auto()
	CH0_FFC_EI_EN = auto()
	CH1_FFC_EI_EN = auto()
	CH0_FFC_PCIE_DET_EN = auto()
	CH1_FFC_PCIE_DET_EN = auto()
	CH0_FFC_PCIE_CT = auto()
	CH1_FFC_PCIE_CT = auto()
	CH0_FFC_SB_INV_RX = auto()
	CH1_FFC_SB_INV_RX = auto()
	CH0_FFC_ENABLE_CGALIGN = auto()
	CH1_FFC_ENABLE_CGALIGN = auto()
	CH0_FFC_SIGNAL_DETECT = auto()
	CH1_FFC_SIGNAL_DETECT = auto()
	CH0_FFC_FB_LOOPBACK = auto()
	CH1_FFC_FB_LOOPBACK = auto()
	CH0_FFC_SB_PFIFO_LP = auto()
	CH1_FFC_SB_PFIFO_LP = auto()
	CH0_FFC_PFIFO_CLR = auto()
	CH1_FFC_PFIFO_CLR = auto()
	CH0_FFC_RATE_MODE_RX = auto()
	CH1_FFC_RATE_MODE_RX = auto()
	CH0_FFC_RATE_MODE_TX = auto()
	CH1_FFC_RATE_MODE_TX = auto()
	CH0_FFC_DIV11_MODE_RX = auto()
	CH1_FFC_DIV11_MODE_RX = auto()
	CH0_FFC_RX_GEAR_MODE = auto()
	CH1_FFC_RX_GEAR_MODE = auto()
	CH0_FFC_TX_GEAR_MODE = auto()
	CH1_FFC_TX_GEAR_MODE = auto()
	CH0_FFC_DIV11_MODE_TX = auto()
	CH1_FFC_DIV11_MODE_TX = auto()
	CH0_FFC_LDR_CORE2TX_EN = auto()
	CH1_FFC_LDR_CORE2TX_EN = auto()
	CH0_FFC_LANE_TX_RST = auto()
	CH1_FFC_LANE_TX_RST = auto()
	CH0_FFC_LANE_RX_RST = auto()
	CH1_FFC_LANE_RX_RST = auto()
	CH0_FFC_RRST = auto()
	CH1_FFC_RRST = auto()
	CH0_FFC_TXPWDNB = auto()
	CH1_FFC_TXPWDNB = auto()
	CH0_FFC_RXPWDNB = auto()
	CH1_FFC_RXPWDNB = auto()
	CH0_LDR_CORE2TX = auto()
	CH1_LDR_CORE2TX = auto()
	D_SCIWDATA0 = auto()
	D_SCIWDATA1 = auto()
	D_SCIWDATA2 = auto()
	D_SCIWDATA3 = auto()
	D_SCIWDATA4 = auto()
	D_SCIWDATA5 = auto()
	D_SCIWDATA6 = auto()
	D_SCIWDATA7 = auto()
	D_SCIADDR0 = auto()
	D_SCIADDR1 = auto()
	D_SCIADDR2 = auto()
	D_SCIADDR3 = auto()
	D_SCIADDR4 = auto()
	D_SCIADDR5 = auto()
	D_SCIENAUX = auto()
	D_SCISELAUX = auto()
	CH0_SCIEN = auto()
	CH1_SCIEN = auto()
	CH0_SCISEL = auto()
	CH1_SCISEL = auto()
	D_SCIRD = auto()
	D_SCIWSTN = auto()
	D_CYAWSTN = auto()
	D_FFC_SYNC_TOGGLE = auto()
	D_FFC_DUAL_RST = auto()
	D_FFC_MACRO_RST = auto()
	D_FFC_MACROPDB = auto()
	D_FFC_TRST = auto()
	CH0_FFC_CDR_EN_BITSLIP = auto()
	CH1_FFC_CDR_EN_BITSLIP = auto()
	D_SCAN_ENABLE = auto()
	D_SCAN_IN_0 = auto()
	D_SCAN_IN_1 = auto()
	D_SCAN_IN_2 = auto()
	D_SCAN_IN_3 = auto()
	D_SCAN_IN_4 = auto()
	D_SCAN_IN_5 = auto()
	D_SCAN_IN_6 = auto()
	D_SCAN_IN_7 = auto()
	D_SCAN_MODE = auto()
	D_SCAN_RESET = auto()
	D_CIN0 = auto()
	D_CIN1 = auto()
	D_CIN2 = auto()
	D_CIN3 = auto()
	D_CIN4 = auto()
	D_CIN5 = auto()
	D_CIN6 = auto()
	D_CIN7 = auto()
	D_CIN8 = auto()
	D_CIN9 = auto()
	D_CIN10 = auto()
	D_CIN11 = auto()
	CH0_HDOUTP = auto()
	CH1_HDOUTP = auto()
	CH0_HDOUTN = auto()
	CH1_HDOUTN = auto()
	D_TXBIT_CLKP_TO_ND = auto()
	D_TXBIT_CLKN_TO_ND = auto()
	D_SYNC_PULSE2ND = auto()
	D_TXPLL_LOL_TO_ND = auto()
	CH0_FF_RX_F_CLK = auto()
	CH1_FF_RX_F_CLK = auto()
	CH0_FF_RX_H_CLK = auto()
	CH1_FF_RX_H_CLK = auto()
	CH0_FF_TX_F_CLK = auto()
	CH1_FF_TX_F_CLK = auto()
	CH0_FF_TX_H_CLK = auto()
	CH1_FF_TX_H_CLK = auto()
	CH0_FF_RX_PCLK = auto()
	CH1_FF_RX_PCLK = auto()
	CH0_FF_TX_PCLK = auto()
	CH1_FF_TX_PCLK = auto()
	CH0_FF_RX_D_0 = auto()
	CH1_FF_RX_D_0 = auto()
	CH0_FF_RX_D_1 = auto()
	CH1_FF_RX_D_1 = auto()
	CH0_FF_RX_D_2 = auto()
	CH1_FF_RX_D_2 = auto()
	CH0_FF_RX_D_3 = auto()
	CH1_FF_RX_D_3 = auto()
	CH0_FF_RX_D_4 = auto()
	CH1_FF_RX_D_4 = auto()
	CH0_FF_RX_D_5 = auto()
	CH1_FF_RX_D_5 = auto()
	CH0_FF_RX_D_6 = auto()
	CH1_FF_RX_D_6 = auto()
	CH0_FF_RX_D_7 = auto()
	CH1_FF_RX_D_7 = auto()
	CH0_FF_RX_D_8 = auto()
	CH1_FF_RX_D_8 = auto()
	CH0_FF_RX_D_9 = auto()
	CH1_FF_RX_D_9 = auto()
	CH0_FF_RX_D_10 = auto()
	CH1_FF_RX_D_10 = auto()
	CH0_FF_RX_D_11 = auto()
	CH1_FF_RX_D_11 = auto()
	CH0_FF_RX_D_12 = auto()
	CH1_FF_RX_D_12 = auto()
	CH0_FF_RX_D_13 = auto()
	CH1_FF_RX_D_13 = auto()
	CH0_FF_RX_D_14 = auto()
	CH1_FF_RX_D_14 = auto()
	CH0_FF_RX_D_15 = auto()
	CH1_FF_RX_D_15 = auto()
	CH0_FF_RX_D_16 = auto()
	CH1_FF_RX_D_16 = auto()
	CH0_FF_RX_D_17 = auto()
	CH1_FF_RX_D_17 = auto()
	CH0_FF_RX_D_18 = auto()
	CH1_FF_RX_D_18 = auto()
	CH0_FF_RX_D_19 = auto()
	CH1_FF_RX_D_19 = auto()
	CH0_FF_RX_D_20 = auto()
	CH1_FF_RX_D_20 = auto()
	CH0_FF_RX_D_21 = auto()
	CH1_FF_RX_D_21 = auto()
	CH0_FF_RX_D_22 = auto()
	CH1_FF_RX_D_22 = auto()
	CH0_FF_RX_D_23 = auto()
	CH1_FF_RX_D_23 = auto()
	CH0_FFS_PCIE_DONE = auto()
	CH1_FFS_PCIE_DONE = auto()
	CH0_FFS_PCIE_CON = auto()
	CH1_FFS_PCIE_CON = auto()
	CH0_FFS_RLOS = auto()
	CH1_FFS_RLOS = auto()
	CH0_FFS_LS_SYNC_STATUS = auto()
	CH1_FFS_LS_SYNC_STATUS = auto()
	CH0_FFS_CC_UNDERRUN = auto()
	CH1_FFS_CC_UNDERRUN = auto()
	CH0_FFS_CC_OVERRUN = auto()
	CH1_FFS_CC_OVERRUN = auto()
	CH0_FFS_RXFBFIFO_ERROR = auto()
	CH1_FFS_RXFBFIFO_ERROR = auto()
	CH0_FFS_TXFBFIFO_ERROR = auto()
	CH1_FFS_TXFBFIFO_ERROR = auto()
	CH0_FFS_RLOL = auto()
	CH1_FFS_RLOL = auto()
	CH0_FFS_SKP_ADDED = auto()
	CH1_FFS_SKP_ADDED = auto()
	CH0_FFS_SKP_DELETED = auto()
	CH1_FFS_SKP_DELETED = auto()
	CH0_LDR_RX2CORE = auto()
	CH1_LDR_RX2CORE = auto()
	D_SCIRDATA0 = auto()
	D_SCIRDATA1 = auto()
	D_SCIRDATA2 = auto()
	D_SCIRDATA3 = auto()
	D_SCIRDATA4 = auto()
	D_SCIRDATA5 = auto()
	D_SCIRDATA6 = auto()
	D_SCIRDATA7 = auto()
	D_SCIINT = auto()
	D_SCAN_OUT_0 = auto()
	D_SCAN_OUT_1 = auto()
	D_SCAN_OUT_2 = auto()
	D_SCAN_OUT_3 = auto()
	D_SCAN_OUT_4 = auto()
	D_SCAN_OUT_5 = auto()
	D_SCAN_OUT_6 = auto()
	D_SCAN_OUT_7 = auto()
	D_COUT0 = auto()
	D_COUT1 = auto()
	D_COUT2 = auto()
	D_COUT3 = auto()
	D_COUT4 = auto()
	D_COUT5 = auto()
	D_COUT6 = auto()
	D_COUT7 = auto()
	D_COUT8 = auto()
	D_COUT9 = auto()
	D_COUT10 = auto()
	D_COUT11 = auto()
	D_COUT12 = auto()
	D_COUT13 = auto()
	D_COUT14 = auto()
	D_COUT15 = auto()
	D_COUT16 = auto()
	D_COUT17 = auto()
	D_COUT18 = auto()
	D_COUT19 = auto()
	D_REFCLKI = auto()
	D_FFS_PLOL = auto()
	PCSCLKDIV = auto()
	SEL2 = auto()
	SEL1 = auto()
	SEL0 = auto()
	CDIV1 = auto()
	DP16KD_REGMODE_A_NOREG_REGMODE_B_NOREG = auto()
	DP16KD_REGMODE_A_NOREG_REGMODE_B_OUTREG = auto()
	DP16KD_REGMODE_A_OUTREG_REGMODE_B_NOREG = auto()
	DP16KD_REGMODE_A_OUTREG_REGMODE_B_OUTREG = auto()
	DP16KD_WRITEMODE_A_NORMAL_WRITEMODE_B_NORMAL = auto()
	DP16KD_WRITEMODE_A_NORMAL_WRITEMODE_B_READBEFOREWRITE = auto()
	DP16KD_WRITEMODE_A_NORMAL_WRITEMODE_B_WRITETHROUGH = auto()
	PIO_IOTYPE_LVCMOS12 = auto()
	PIO_IOTYPE_LVCMOS15 = auto()
	PIO_IOTYPE_LVCMOS18 = auto()
	PIO_IOTYPE_LVCMOS25 = auto()
	PIO_IOTYPE_LVCMOS33 = auto()
	PIO_IOTYPE_LVDS = auto()
	PIO_IOTYPE_SSTL15_I = auto()
	PIO_IOTYPE_SSTL15_II = auto()
	PIO_IOTYPE_SSTL18_I = auto()
	PIO_IOTYPE_SSTL18_II = auto()
	SCCU2C = auto()
	SDPRAME = auto()
	SLOGICB = auto()
	SRAMWB = auto()
	PAD = auto()
	PADDI = auto()
	PADDO = auto()
	PADDT = auto()
	IOLOGIC = auto()
	SIOLOGIC = auto()
	DI = auto()
	IOLDO = auto()
	IOLDOD = auto()
	IOLDOI = auto()
	IOLTO = auto()
	INDD = auto()
	LOADN = auto()
	MOVE = auto()
	DIRECTION = auto()
	TSDATA0 = auto()
	TXDATA0 = auto()
	TXDATA1 = auto()
	RXDATA0 = auto()
	RXDATA1 = auto()
	INFF = auto()
	CFLAG = auto()
	ECLK = auto()
	TSDATA1 = auto()
	TXDATA2 = auto()
	TXDATA3 = auto()
	RXDATA2 = auto()
	RXDATA3 = auto()
	TXDATA4 = auto()
	TXDATA5 = auto()
	TXDATA6 = auto()
	RXDATA4 = auto()
	RXDATA5 = auto()
	RXDATA6 = auto()
	DQSR90 = auto()
	DQSW270 = auto()
	DQSW = auto()
	RDPNTR0 = auto()
	RDPNTR1 = auto()
	RDPNTR2 = auto()
	WRPNTR0 = auto()
	WRPNTR1 = auto()
	WRPNTR2 = auto()
	SLIP = auto()
	GSR = auto()
	JTAGG = auto()
	TCK = auto()
	TMS = auto()
	TDI = auto()
	JTDO2 = auto()
	JTDO1 = auto()
	TDO = auto()
	JTDI = auto()
	JTCK = auto()
	JRTI2 = auto()
	JRTI1 = auto()
	JSHIFT = auto()
	JUPDATE = auto()
	JRSTN = auto()
	JCE2 = auto()
	JCE1 = auto()
	OSCG = auto()
	OSC = auto()
	SEDSTDBY = auto()
	SEDGA = auto()
	SEDENABLE = auto()
	SEDSTART = auto()
	SEDFRCERR = auto()
	SEDDONE = auto()
	SEDINPROG = auto()
	SEDERR = auto()
	DTR = auto()
	STARTPULSE = auto()
	DTROUT0 = auto()
	DTROUT1 = auto()
	DTROUT2 = auto()
	DTROUT3 = auto()
	DTROUT4 = auto()
	DTROUT5 = auto()
	DTROUT6 = auto()
	DTROUT7 = auto()
	USRMCLK = auto()
	CLKDIVF = auto()
	ALIGNWD = auto()
	CDIVX = auto()
	ECLKSYNCB = auto()
	ECLKI = auto()
	STOP = auto()
	ECLKO = auto()
	DLLDELD = auto()
	A = auto()
	DDRDEL = auto()
	Z = auto()
	DDRDLL = auto()
	UDDCNTLN = auto()
	FREEZE = auto()
	DIVOSC = auto()
	DCNTL0 = auto()
	DCNTL1 = auto()
	DCNTL2 = auto()
	DCNTL3 = auto()
	DCNTL4 = auto()
	DCNTL5 = auto()
	DCNTL6 = auto()
	DCNTL7 = auto()
	DQSBUFM = auto()
	DQSI = auto()
	READ1 = auto()
	READ0 = auto()
	READCLKSEL2 = auto()
	READCLKSEL1 = auto()
	READCLKSEL0 = auto()
	DYNDELAY0 = auto()
	DYNDELAY1 = auto()
	DYNDELAY2 = auto()
	DYNDELAY3 = auto()
	DYNDELAY4 = auto()
	DYNDELAY5 = auto()
	DYNDELAY6 = auto()
	DYNDELAY7 = auto()
	PAUSE = auto()
	RDLOADN = auto()
	RDMOVE = auto()
	RDDIRECTION = auto()
	WRLOADN = auto()
	WRMOVE = auto()
	WRDIRECTION = auto()
	DATAVALID = auto()
	BURSTDET = auto()
	RDCFLAG = auto()
	WRCFLAG = auto()
	SCLK = auto()
	TRELLIS_ECLKBUF = auto()
	MULT18X18D_REGS_ALL = auto()
	MULT18X18D_REGS_INPUT = auto()
	MULT18X18D_REGS_NONE = auto()
	MULT18X18D_REGS_OUTPUT = auto()
	MULT18X18D_REGS_PIPELINE = auto()
	P = auto()
	ECLKBRIDGECS = auto()
	SEL = auto()
	ECSOUT = auto()
	WIRE_TYPE_NONE = auto()
	WIRE_TYPE_SLICE = auto()
	WIRE_TYPE_DQS = auto()
	WIRE_TYPE_IOLOGIC = auto()
	WIRE_TYPE_SIOLOGIC = auto()
	WIRE_TYPE_PIO = auto()
	WIRE_TYPE_EBR = auto()
	WIRE_TYPE_MULT18 = auto()
	WIRE_TYPE_ALU54 = auto()
	WIRE_TYPE_DDRDLL = auto()
	WIRE_TYPE_CCLK = auto()
	WIRE_TYPE_EXTREF = auto()
	WIRE_TYPE_DCU = auto()
	WIRE_TYPE_PLL = auto()
	WIRE_TYPE_SED = auto()
	WIRE_TYPE_OSC = auto()
	WIRE_TYPE_JTAG = auto()
	WIRE_TYPE_GSR = auto()
	WIRE_TYPE_DTR = auto()
	WIRE_TYPE_PCSCLKDIV = auto()
	WIRE_TYPE_H00 = auto()
	WIRE_TYPE_H01 = auto()
	WIRE_TYPE_H02 = auto()
	WIRE_TYPE_H06 = auto()
	WIRE_TYPE_V00 = auto()
	WIRE_TYPE_V01 = auto()
	WIRE_TYPE_V02 = auto()
	WIRE_TYPE_V06 = auto()
	WIRE_TYPE_G_HPBX = auto()
	WIRE_TYPE_G_VPTX = auto()
	WIRE_TYPE_L_HPBX = auto()
	WIRE_TYPE_R_HPBX = auto()
	IOLOGIC_MODE_IDDRX1F = auto()
	IOLOGIC_MODE_IDDRX2F = auto()
	IOLOGIC_MODE_IREG = auto()
	IOLOGIC_MODE_ODDRX1F = auto()
	IOLOGIC_MODE_ODDRX2F = auto()
	IOLOGIC_MODE_OREG = auto()
	IOLOGIC_MODE_TSREG = auto()
	DCSC = auto()
	DCSOUT = auto()
	MODESEL = auto()
	ALUT = auto()
	ASYNC_RESET_RELEASE = auto()
	BEL = auto()
	BLUT = auto()
	C = auto()
	CCU2C = auto()
	CCU2_INJECT1_0 = auto()
	CCU2_INJECT1_1 = auto()
	CEAMUX = auto()
	CEBMUX = auto()
	CEIMUX = auto()
	CEMUX = auto()
	CEOMUX = auto()
	CER = auto()
	CEW = auto()
	CH0_AUTO_CALIB_EN = auto()
	CH0_AUTO_FACQ_EN = auto()
	CH0_BAND_THRESHOLD = auto()
	CH0_CALIB_CK_MODE = auto()
	CH0_CC_MATCH_1 = auto()
	CH0_CC_MATCH_2 = auto()
	CH0_CC_MATCH_3 = auto()
	CH0_CC_MATCH_4 = auto()
	CH0_CDR_CNT4SEL = auto()
	CH0_CDR_CNT8SEL = auto()
	CH0_CTC_BYPASS = auto()
	CH0_DCOATDCFG = auto()
	CH0_DCOATDDLY = auto()
	CH0_DCOBYPSATD = auto()
	CH0_DCOCALDIV = auto()
	CH0_DCOCTLGI = auto()
	CH0_DCODISBDAVOID = auto()
	CH0_DCOFLTDAC = auto()
	CH0_DCOFTNRG = auto()
	CH0_DCOIOSTUNE = auto()
	CH0_DCOITUNE = auto()
	CH0_DCOITUNE4LSB = auto()
	CH0_DCOIUPDNX2 = auto()
	CH0_DCONUOFLSB = auto()
	CH0_DCOSCALEI = auto()
	CH0_DCOSTARTVAL = auto()
	CH0_DCOSTEP = auto()
	CH0_DEC_BYPASS = auto()
	CH0_ENABLE_CG_ALIGN = auto()
	CH0_ENC_BYPASS = auto()
	CH0_FF_RX_F_CLK_DIS = auto()
	CH0_FF_RX_H_CLK_EN = auto()
	CH0_FF_TX_F_CLK_DIS = auto()
	CH0_FF_TX_H_CLK_EN = auto()
	CH0_GE_AN_ENABLE = auto()
	CH0_INVERT_RX = auto()
	CH0_INVERT_TX = auto()
	CH0_LDR_CORE2TX_SEL = auto()
	CH0_LDR_RX2CORE_SEL = auto()
	CH0_LEQ_OFFSET_SEL = auto()
	CH0_LEQ_OFFSET_TRIM = auto()
	CH0_LSM_DISABLE = auto()
	CH0_MATCH_2_ENABLE = auto()
	CH0_MATCH_4_ENABLE = auto()
	CH0_MIN_IPG_CNT = auto()
	CH0_PCIE_EI_EN = auto()
	CH0_PCIE_MODE = auto()
	CH0_PCS_DET_TIME_SEL = auto()
	CH0_PDEN_SEL = auto()
	CH0_PRBS_ENABLE = auto()
	CH0_PRBS_LOCK = auto()
	CH0_PRBS_SELECTION = auto()
	CH0_RATE_MODE_RX = auto()
	CH0_RATE_MODE_TX = auto()
	CH0_RCV_DCC_EN = auto()
	CH0_REG_BAND_OFFSET = auto()
	CH0_REG_BAND_SEL = auto()
	CH0_REG_IDAC_EN = auto()
	CH0_REG_IDAC_SEL = auto()
	CH0_REQ_EN = auto()
	CH0_REQ_LVL_SET = auto()
	CH0_RIO_MODE = auto()
	CH0_RLOS_SEL = auto()
	CH0_RPWDNB = auto()
	CH0_RTERM_RX = auto()
	CH0_RTERM_TX = auto()
	CH0_RXIN_CM = auto()
	CH0_RXTERM_CM = auto()
	CH0_RX_DCO_CK_DIV = auto()
	CH0_RX_DIV11_SEL = auto()
	CH0_RX_GEAR_BYPASS = auto()
	CH0_RX_GEAR_MODE = auto()
	CH0_RX_LOS_CEQ = auto()
	CH0_RX_LOS_EN = auto()
	CH0_RX_LOS_HYST_EN = auto()
	CH0_RX_LOS_LVL = auto()
	CH0_RX_RATE_SEL = auto()
	CH0_RX_SB_BYPASS = auto()
	CH0_SB_BYPASS = auto()
	CH0_SEL_SD_RX_CLK = auto()
	CH0_TDRV_DAT_SEL = auto()
	CH0_TDRV_POST_EN = auto()
	CH0_TDRV_PRE_EN = auto()
	CH0_TDRV_SLICE0_CUR = auto()
	CH0_TDRV_SLICE0_SEL = auto()
	CH0_TDRV_SLICE1_CUR = auto()
	CH0_TDRV_SLICE1_SEL = auto()
	CH0_TDRV_SLICE2_CUR = auto()
	CH0_TDRV_SLICE2_SEL = auto()
	CH0_TDRV_SLICE3_CUR = auto()
	CH0_TDRV_SLICE3_SEL = auto()
	CH0_TDRV_SLICE4_CUR = auto()
	CH0_TDRV_SLICE4_SEL = auto()
	CH0_TDRV_SLICE5_CUR = auto()
	CH0_TDRV_SLICE5_SEL = auto()
	CH0_TPWDNB = auto()
	CH0_TX_CM_SEL = auto()
	CH0_TX_DIV11_SEL = auto()
	CH0_TX_GEAR_BYPASS = auto()
	CH0_TX_GEAR_MODE = auto()
	CH0_TX_POST_SIGN = auto()
	CH0_TX_PRE_SIGN = auto()
	CH0_UC_MODE = auto()
	CH0_UDF_COMMA_A = auto()
	CH0_UDF_COMMA_B = auto()
	CH0_UDF_COMMA_MASK = auto()
	CH0_WA_BYPASS = auto()
	CH0_WA_MODE = auto()
	CH1_AUTO_CALIB_EN = auto()
	CH1_AUTO_FACQ_EN = auto()
	CH1_BAND_THRESHOLD = auto()
	CH1_CALIB_CK_MODE = auto()
	CH1_CC_MATCH_1 = auto()
	CH1_CC_MATCH_2 = auto()
	CH1_CC_MATCH_3 = auto()
	CH1_CC_MATCH_4 = auto()
	CH1_CDR_CNT4SEL = auto()
	CH1_CDR_CNT8SEL = auto()
	CH1_CTC_BYPASS = auto()
	CH1_DCOATDCFG = auto()
	CH1_DCOATDDLY = auto()
	CH1_DCOBYPSATD = auto()
	CH1_DCOCALDIV = auto()
	CH1_DCOCTLGI = auto()
	CH1_DCODISBDAVOID = auto()
	CH1_DCOFLTDAC = auto()
	CH1_DCOFTNRG = auto()
	CH1_DCOIOSTUNE = auto()
	CH1_DCOITUNE = auto()
	CH1_DCOITUNE4LSB = auto()
	CH1_DCOIUPDNX2 = auto()
	CH1_DCONUOFLSB = auto()
	CH1_DCOSCALEI = auto()
	CH1_DCOSTARTVAL = auto()
	CH1_DCOSTEP = auto()
	CH1_DEC_BYPASS = auto()
	CH1_ENABLE_CG_ALIGN = auto()
	CH1_ENC_BYPASS = auto()
	CH1_FF_RX_F_CLK_DIS = auto()
	CH1_FF_RX_H_CLK_EN = auto()
	CH1_FF_TX_F_CLK_DIS = auto()
	CH1_FF_TX_H_CLK_EN = auto()
	CH1_GE_AN_ENABLE = auto()
	CH1_INVERT_RX = auto()
	CH1_INVERT_TX = auto()
	CH1_LDR_CORE2TX_SEL = auto()
	CH1_LDR_RX2CORE_SEL = auto()
	CH1_LEQ_OFFSET_SEL = auto()
	CH1_LEQ_OFFSET_TRIM = auto()
	CH1_LSM_DISABLE = auto()
	CH1_MATCH_2_ENABLE = auto()
	CH1_MATCH_4_ENABLE = auto()
	CH1_MIN_IPG_CNT = auto()
	CH1_PCIE_EI_EN = auto()
	CH1_PCIE_MODE = auto()
	CH1_PCS_DET_TIME_SEL = auto()
	CH1_PDEN_SEL = auto()
	CH1_PRBS_ENABLE = auto()
	CH1_PRBS_LOCK = auto()
	CH1_PRBS_SELECTION = auto()
	CH1_RATE_MODE_RX = auto()
	CH1_RATE_MODE_TX = auto()
	CH1_RCV_DCC_EN = auto()
	CH1_REG_BAND_OFFSET = auto()
	CH1_REG_BAND_SEL = auto()
	CH1_REG_IDAC_EN = auto()
	CH1_REG_IDAC_SEL = auto()
	CH1_REQ_EN = auto()
	CH1_REQ_LVL_SET = auto()
	CH1_RIO_MODE = auto()
	CH1_RLOS_SEL = auto()
	CH1_RPWDNB = auto()
	CH1_RTERM_RX = auto()
	CH1_RTERM_TX = auto()
	CH1_RXIN_CM = auto()
	CH1_RXTERM_CM = auto()
	CH1_RX_DCO_CK_DIV = auto()
	CH1_RX_DIV11_SEL = auto()
	CH1_RX_GEAR_BYPASS = auto()
	CH1_RX_GEAR_MODE = auto()
	CH1_RX_LOS_CEQ = auto()
	CH1_RX_LOS_EN = auto()
	CH1_RX_LOS_HYST_EN = auto()
	CH1_RX_LOS_LVL = auto()
	CH1_RX_RATE_SEL = auto()
	CH1_RX_SB_BYPASS = auto()
	CH1_SB_BYPASS = auto()
	CH1_SEL_SD_RX_CLK = auto()
	CH1_TDRV_DAT_SEL = auto()
	CH1_TDRV_POST_EN = auto()
	CH1_TDRV_PRE_EN = auto()
	CH1_TDRV_SLICE0_CUR = auto()
	CH1_TDRV_SLICE0_SEL = auto()
	CH1_TDRV_SLICE1_CUR = auto()
	CH1_TDRV_SLICE1_SEL = auto()
	CH1_TDRV_SLICE2_CUR = auto()
	CH1_TDRV_SLICE2_SEL = auto()
	CH1_TDRV_SLICE3_CUR = auto()
	CH1_TDRV_SLICE3_SEL = auto()
	CH1_TDRV_SLICE4_CUR = auto()
	CH1_TDRV_SLICE4_SEL = auto()
	CH1_TDRV_SLICE5_CUR = auto()
	CH1_TDRV_SLICE5_SEL = auto()
	CH1_TPWDNB = auto()
	CH1_TX_CM_SEL = auto()
	CH1_TX_DIV11_SEL = auto()
	CH1_TX_GEAR_BYPASS = auto()
	CH1_TX_GEAR_MODE = auto()
	CH1_TX_POST_SIGN = auto()
	CH1_TX_PRE_SIGN = auto()
	CH1_UC_MODE = auto()
	CH1_UDF_COMMA_A = auto()
	CH1_UDF_COMMA_B = auto()
	CH1_UDF_COMMA_MASK = auto()
	CH1_WA_BYPASS = auto()
	CH1_WA_MODE = auto()
	CIN = auto()
	CLAMP = auto()
	CLK0_DIV = auto()
	CLK1_DIV = auto()
	CLK2_DIV = auto()
	CLK3_DIV = auto()
	CLKAMUX = auto()
	CLKBMUX = auto()
	CLKFB_DIV = auto()
	CLKIMUX = auto()
	CLKI_DIV = auto()
	CLKOMUX = auto()
	CLKOP_DIV = auto()
	CLKOP_ENABLE = auto()
	CLKOP_TRIM_DELAY = auto()
	CLKOP_TRIM_POL = auto()
	CLKOS2_DIV = auto()
	CLKOS2_ENABLE = auto()
	CLKOS3_DIV = auto()
	CLKOS3_ENABLE = auto()
	CLKOS_DIV = auto()
	CLKOS_ENABLE = auto()
	CLKOS_TRIM_DELAY = auto()
	CLKOS_TRIM_POL = auto()
	CLKR = auto()
	CLKW = auto()
	COUT = auto()
	CSDECODE_A = auto()
	CSDECODE_B = auto()
	D = auto()
	D2 = auto()
	D3 = auto()
	D4 = auto()
	D5 = auto()
	D6 = auto()
	DATAMUX_MDDR = auto()
	DATAMUX_ODDR = auto()
	DATAMUX_OREG = auto()
	DATA_WIDTH_A = auto()
	DATA_WIDTH_B = auto()
	DATA_WIDTH_W = auto()
	DCSMODE = auto()
	DDRDLLA = auto()
	DELAYF = auto()
	DELAYG = auto()
	DEL_MODE = auto()
	DEL_VALUE = auto()
	DIFFRESISTOR = auto()
	DIR = auto()
	DIV = auto()
	DPHASE_SOURCE = auto()
	DQS_LI_DEL_ADJ = auto()
	DQS_LI_DEL_VAL = auto()
	DQS_LO_DEL_ADJ = auto()
	DQS_LO_DEL_VAL = auto()
	DRIVE = auto()
	D_BITCLK_FROM_ND_EN = auto()
	D_BITCLK_LOCAL_EN = auto()
	D_BITCLK_ND_EN = auto()
	D_BUS8BIT_SEL = auto()
	D_CDR_LOL_SET = auto()
	D_CMUSETBIASI = auto()
	D_CMUSETI4CPP = auto()
	D_CMUSETI4CPZ = auto()
	D_CMUSETI4VCO = auto()
	D_CMUSETICP4P = auto()
	D_CMUSETICP4Z = auto()
	D_CMUSETINITVCT = auto()
	D_CMUSETISCL4VCO = auto()
	D_CMUSETP1GM = auto()
	D_CMUSETP2AGM = auto()
	D_CMUSETZGM = auto()
	D_DCO_CALIB_TIME_SEL = auto()
	D_HIGH_MARK = auto()
	D_IB_PWDNB = auto()
	D_ISETLOS = auto()
	D_LOW_MARK = auto()
	D_MACROPDB = auto()
	D_PD_ISET = auto()
	D_PLL_LOL_SET = auto()
	D_REFCK_MODE = auto()
	D_REQ_ISET = auto()
	D_RG_EN = auto()
	D_RG_SET = auto()
	D_SETICONST_AUX = auto()
	D_SETICONST_CH = auto()
	D_SETIRPOLY_AUX = auto()
	D_SETIRPOLY_CH = auto()
	D_SETPLLRC = auto()
	D_SYNC_LOCAL_EN = auto()
	D_SYNC_ND_EN = auto()
	D_TXPLL_PWDNB = auto()
	D_TX_VCO_CK_DIV = auto()
	D_XGE_MODE = auto()
	E = auto()
	ECP5_IS_GLOBAL = auto()
	ER1 = auto()
	ER2 = auto()
	FEEDBK_PATH = auto()
	FORCE_MAX_DELAY = auto()
	FORCE_ZERO_BARREL_SHIFT = auto()
	FREQ_LOCK_ACCURACY = auto()
	GND = auto()
	HYSTERESIS = auto()
	ICP_CURRENT = auto()
	IDDR71B = auto()
	IDDRX1F = auto()
	IDDRX2DQA = auto()
	IDDRX2F = auto()
	INIT = auto()
	INIT0 = auto()
	INIT1 = auto()
	INITVAL = auto()
	INJECT1_0 = auto()
	INJECT1_1 = auto()
	INTFB_WAKE = auto()
	INT_LOCK_STICKY = auto()
	INV = auto()
	IOLTOMUX = auto()
	IO_TYPE = auto()
	KVCO = auto()
	L6MUX21 = auto()
	LEGACY = auto()
	LOC = auto()
	LPF_CAPACITOR = auto()
	LPF_RESISTOR = auto()
	LSRIMUX = auto()
	LSRMODE = auto()
	LSROMUX = auto()
	LUT0_INITVAL = auto()
	LUT1_INITVAL = auto()
	LUT4 = auto()
	M = auto()
	MASK01 = auto()
	MASKPAT = auto()
	MASKPAT_SOURCE = auto()
	MCPAT = auto()
	MCPAT_SOURCE = auto()
	MFG1_TEST = auto()
	MFG2_TEST = auto()
	MFG_ENABLE_FILTEROPAMP = auto()
	MFG_EN_UP = auto()
	MFG_FLOAT_ICP = auto()
	MFG_FORCE_VFILTER = auto()
	MFG_GMCREF_SEL = auto()
	MFG_GMC_GAIN = auto()
	MFG_GMC_PRESET = auto()
	MFG_GMC_RESET = auto()
	MFG_GMC_TEST = auto()
	MFG_ICP_TEST = auto()
	MFG_LF_PRESET = auto()
	MFG_LF_RESET = auto()
	MFG_LF_RESGRND = auto()
	MODE = auto()
	MULT_BYPASS = auto()
	OCEAMUX = auto()
	OCEBMUX = auto()
	OCER = auto()
	ODDR71B = auto()
	ODDRX1F = auto()
	ODDRX2DQA = auto()
	ODDRX2DQSB = auto()
	ODDRX2F = auto()
	OPENDRAIN = auto()
	OSHX2A = auto()
	OUTDIVIDER_MUXA = auto()
	OUTDIVIDER_MUXB = auto()
	OUTDIVIDER_MUXC = auto()
	OUTDIVIDER_MUXD = auto()
	PDPW16KD = auto()
	PFUMX = auto()
	PLLRST_ENA = auto()
	PLL_LOCK_MODE = auto()
	PULLMODE = auto()
	Q = auto()
	Q2 = auto()
	Q3 = auto()
	Q4 = auto()
	Q5 = auto()
	Q6 = auto()
	QWL = auto()
	REFCK_DCBIAS_EN = auto()
	REFCK_PWDNB = auto()
	REFCK_RTERM = auto()
	REFIN_RESET = auto()
	REG0_LSRMODE = auto()
	REG0_REGSET = auto()
	REG0_SD = auto()
	REG1_LSRMODE = auto()
	REG1_REGSET = auto()
	REG1_SD = auto()
	REGMODE = auto()
	REGMODE_A = auto()
	REGMODE_B = auto()
	REGSET = auto()
	REG_FLAG_CLK = auto()
	REG_FLAG_CE = auto()
	REG_FLAG_RST = auto()
	REG_INPUTA_CE = auto()
	REG_INPUTA_CLK = auto()
	REG_INPUTA_RST = auto()
	REG_INPUTB_CE = auto()
	REG_INPUTB_CLK = auto()
	REG_INPUTB_RST = auto()
	REG_INPUTC0_CLK = auto()
	REG_INPUTC0_CE = auto()
	REG_INPUTC0_RST = auto()
	REG_INPUTC1_CLK = auto()
	REG_INPUTC1_CE = auto()
	REG_INPUTC1_RST = auto()
	REG_INPUTC_CLK = auto()
	REG_INPUTC_CE = auto()
	REG_INPUTC_RST = auto()
	REG_INPUTCFB_CLK = auto()
	REG_INPUTCFB_CE = auto()
	REG_INPUTCFB_RST = auto()
	REG_OPCODEIN_0_CE = auto()
	REG_OPCODEIN_0_CLK = auto()
	REG_OPCODEIN_0_RST = auto()
	REG_OPCODEIN_1_CE = auto()
	REG_OPCODEIN_1_CLK = auto()
	REG_OPCODEIN_1_RST = auto()
	REG_OPCODEOP0_0_CE = auto()
	REG_OPCODEOP0_0_CLK = auto()
	REG_OPCODEOP0_0_RST = auto()
	REG_OPCODEOP0_1_CE = auto()
	REG_OPCODEOP0_1_CLK = auto()
	REG_OPCODEOP0_1_RST = auto()
	REG_OPCODEOP1_0_CLK = auto()
	REG_OPCODEOP1_1_CLK = auto()
	REG_OUTPUT0_CLK = auto()
	REG_OUTPUT0_CE = auto()
	REG_OUTPUT0_RST = auto()
	REG_OUTPUT1_CLK = auto()
	REG_OUTPUT1_CE = auto()
	REG_OUTPUT1_RST = auto()
	REG_OUTPUT_CLK = auto()
	REG_OUTPUT_CE = auto()
	REG_OUTPUT_RST = auto()
	REG_PIPELINE_CE = auto()
	REG_PIPELINE_CLK = auto()
	REG_PIPELINE_RST = auto()
	HIGHSPEED_CLK = auto()
	RESETMODE = auto()
	RNDPAT = auto()
	RSTAMUX = auto()
	RSTBMUX = auto()
	S0 = auto()
	S1 = auto()
	SD = auto()
	SGSR = auto()
	SLEWRATE = auto()
	SOURCEB_MODE = auto()
	STDBY_ENABLE = auto()
	SYNCMODE = auto()
	SYNC_ENABLE = auto()
	T0 = auto()
	T1 = auto()
	TERMINATION = auto()
	TILE_WIRE_ID = auto()
	TRELLIS_DPR16X4 = auto()
	TRELLIS_FF = auto()
	TRIMUX_TSREG = auto()
	TSHX2DQA = auto()
	TSHX2DQSA = auto()
	USRMCLKI = auto()
	USRMCLKO = auto()
	USRMCLKTS = auto()
	VCC = auto()
	WCKMUX = auto()
	WEAMUX = auto()
	WEBMUX = auto()
	WID = auto()
	WREMUX = auto()
	WRITEMODE_A = auto()
	WRITEMODE_B = auto()
	Y = auto()
	ioff_dir = auto()
	lfe5u_12f = auto()
	lfe5u_25f = auto()
	lfe5u_45f = auto()
	lfe5u_85f = auto()
	lfe5um5g_25f = auto()
	lfe5um5g_45f = auto()
	lfe5um5g_85f = auto()
	lfe5um_25f = auto()
	lfe5um_45f = auto()
	lfe5um_85f = auto()
	noglobal = auto()
	pack = auto()
	place = auto()
	placer = auto()
	route = auto()
	router = auto()
	syn_useioff = auto()
	TRELLIS_COMB = auto()
	TRELLIS_RAMW = auto()
	TRELLIS_COMB_CARRY0 = auto()
	TRELLIS_COMB_CARRY1 = auto()
	WD = auto()
	OFX = auto()
	F = auto()
	CCU2_INJECT1 = auto()
	DB_CONST_ID_COUNT = auto()

class Location:
	x: SupportsInt
	y: SupportsInt

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, x: SupportsInt, y: SupportsInt) -> None:
		...

	def __eq__(self, other: Location) -> bool:
		...

	def __ne__(self, other: Location) -> bool:
		...

	def __gt__(self, other: Location) -> bool:
		...

	def __repr__(self) -> str:
		...

	def __hash__(self) -> int:
		...

class BelID:
	location: Location
	index: SupportsInt

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, location: Location, index: SupportsInt) -> None:
		...

	def __eq__(self, other: BelID) -> bool:
		...

	def __ne__(self, other: BelID) -> bool:
		...

	def __gt__(self, other: BelID) -> bool:
		...

	def __repr__(self) -> str:
		...

	def __hash__(self) -> int:
		...

class BelPin:
	bel: BelID
	pin: IdString

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, bel: BelID, pin: IdString) -> None:
		...

	def __repr__(self) -> str:
		...

class WireID:
	location: Location
	index: SupportsInt

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, location: Location, index: SupportsInt) -> None:
		...

	def __eq__(self, other: WireID) -> bool:
		...

	def __ne__(self, other: WireID) -> bool:
		...

	def __gt__(self, other: WireID) -> bool:
		...

	def __repr__(self) -> str:
		...

	def __hash__(self) -> int:
		...

class PipID:
	location: Location
	index: SupportsInt

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, location: Location, index: SupportsInt) -> None:
		...

	def __eq__(self, other: PipID) -> bool:
		...

	def __ne__(self, other: PipID) -> bool:
		...

	def __gt__(self, other: PipID) -> bool:
		...

	def __repr__(self) -> str:
		...

	def __hash__(self) -> int:
		...

class PipMap:
	pip: PipID
	strength: PlaceStrength

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, pip: PipID, strength: PlaceStrength) -> None:
		...

	def __repr__(self) -> str:
		...

class GroupID:
	@unique
	class Type(Enum):
		NONE = auto()
		SWITCHBOX = auto()

	type: GroupID.Type
	location: Location

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, type: GroupID.Type, location: Location) -> None:
		...

	def __eq__(self, other: GroupID) -> bool:
		...

	def __ne__(self, other: GroupID) -> bool:
		...

	def __repr__(self) -> str:
		...

	def __hash__(self) -> int:
		...

GroupIDType: TypeAlias = GroupID.Type

class DecalID:
	@unique
	class Type(Enum):
		NONE = auto()
		BEL = auto()
		WIRE = auto()
		PIP = auto()
		GROUP = auto()

	type: Type
	location: Location
	z: SupportsInt
	active: bool

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, type: DecalID.Type, location: Location, z: SupportsInt, active: bool) -> None:
		...

	def __eq__(self, other: DecalID) -> bool:
		...

	def __ne__(self, other: DecalID) -> bool:
		...

	def __repr__(self) -> str:
		...

	def __hash__(self) -> int:
		...

DecalIDType: TypeAlias = DecalID.Type

class DecalXY:
	decal: DecalID
	x: SupportsFloat
	y: SupportsFloat

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, decal: DecalID, x: SupportsFloat, y: SupportsFloat) -> None:
		...

class ArchNetInfo:
	is_global: bool

	@overload
	def __init__(self) -> None:
		...

	@overload
	def __init__(self, is_global: bool) -> None:
		...

	def __repr__(self) -> str:
		...

class ArchCellInfo:
	@unique
	class CombFlags(Flag):
		NONE = 0x00
		CARRY = 0x01
		LUTRAM = 0x02
		MUX5 = 0x04
		MUX6 = 0x08
		RAM_WCKINV = 0x10
		RAM_WREINV = 0x20
		RAMW_BLOCK = 0x40

	@unique
	class FFFlags(Flag):
		NONE = 0x00
		CLKINV = 0x01
		CEINV = 0x02
		CECONST = 0x04
		LSRINV = 0x08
		GSREN = 0x10
		ASYNC = 0x20
		M_USED = 0x40

	class CombInfo:
		flags: ArchCellInfo.CombFlags
		ram_wck: object
		ram_wre: object
		mux_fxad: object

	class FFInfo:
		flags: ArchCellInfo.FFFlags
		clk_sig: object
		lsr_sig: object
		ce_sig: object
		de_sig: object

	class RAMInfo:
		is_pdp: bool
		is_output_a_registered: bool
		is_output_b_registered: bool
		regmode_timing_id: object

	class MultInfo:
		is_clocked: bool
		timing_id: object

	comb_info: ArchCellInfo.CombInfo
	ff_info: ArchCellInfo.FFInfo
	ram_info: ArchCellInfo.RAMInfo
	mult_info: ArchCellInfo.MultInfo

ArchCellInfoCombFlags: TypeAlias = ArchCellInfo.CombFlags
ArchCellInfoFFFlags: TypeAlias = ArchCellInfo.FFFlags
ArchCellInfoCombInfo: TypeAlias = ArchCellInfo.CombInfo
ArchCellInfoFFInfo: TypeAlias = ArchCellInfo.FFInfo
ArchCellInfoRAMInfo: TypeAlias = ArchCellInfo.RAMInfo
ArchCellInfoMultInfo: TypeAlias = ArchCellInfo.MultInfo
